version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: tasks_user
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: tasksdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:
