name: App CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tasks-backend:latest

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/tasks-backend:latest
          format: table
          exit-code: 1
          ignore-unfixed: true

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Set Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Deploy App with Helm
        run: |
          helm upgrade --install tasks-app ./helm/tasks-app \
            --set backend.image=${{ secrets.DOCKERHUB_USERNAME }}/tasks-backend:latest

